services:
  php:
    image: php:8.4-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./config:/etc/apache2/sites-available
      - ./config:/etc/apache2/sites-enabled
      - ./logs:/var/log/apache2
    command: 
      - /bin/bash 
      - -c 
      - |        
        a2enmod rewrite
        a2ensite apache2.conf
        apachectl -D FOREGROUND